config/routes.rb
# == Route Map
#
#                    Prefix Verb   URI Pattern                                                                              Controller#Action
#             user_comments POST   /users/:user_id/comments(.:format)                                                       comments#create
#                     users GET    /users(.:format)                                                                         users#index
#                           POST   /users(.:format)                                                                         users#create
#                  new_user GET    /users/new(.:format)                                                                     users#new
#                 edit_user GET    /users/:id/edit(.:format)                                                                users#edit
#                      user GET    /users/:id(.:format)                                                                     users#show
#                           PATCH  /users/:id(.:format)                                                                     users#update
#                           PUT    /users/:id(.:format)                                                                     users#update
#                           DELETE /users/:id(.:format)                                                                     users#destroy
#             goal_comments POST   /goals/:goal_id/comments(.:format)                                                       comments#create
#                     goals POST   /goals(.:format)                                                                         goals#create
#                  new_goal GET    /goals/new(.:format)                                                                     goals#new
#                 edit_goal GET    /goals/:id/edit(.:format)                                                                goals#edit
#                      goal GET    /goals/:id(.:format)                                                                     goals#show
#                           PATCH  /goals/:id(.:format)                                                                     goals#update
#                           PUT    /goals/:id(.:format)                                                                     goals#update
#                           DELETE /goals/:id(.:format)                                                                     goals#destroy
#              edit_comment GET    /comments/:id/edit(.:format)                                                             comments#edit
#                   comment PATCH  /comments/:id(.:format)                                                                  comments#update
#                           PUT    /comments/:id(.:format)                                                                  comments#update
#                           DELETE /comments/:id(.:format)                                                                  comments#destroy
#               new_session GET    /session/new(.:format)                                                                   sessions#new
#              edit_session GET    /session/edit(.:format)                                                                  sessions#edit
#                   session GET    /session(.:format)                                                                       sessions#show
#                           PATCH  /session(.:format)                                                                       sessions#update
#                           PUT    /session(.:format)                                                                       sessions#update
#                           DELETE /session(.:format)                                                                       sessions#destroy
#                           POST   /session(.:format)                                                                       sessions#create
#                      root GET    /                                                                                        users#new
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  resources :users do
    resources :comments, only: :create
  end
  resources :goals, except: :index do
    resources :comments, only: :create
  end
  resources :comments, only: [:edit, :update, :destroy]
  resource :session

  root to: "users#new"
end

app/models/goal.rb
# == Schema Information
#
# Table name: goals
#
#  id          :bigint           not null, primary key
#  title       :string           not null
#  description :text
#  is_complete :boolean          default(FALSE), not null
#  is_private  :boolean          default(FALSE), not null
#  creator_id  :bigint
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Goal < ApplicationRecord
    include Commentable

    validates :title, presence: true
    validates :description, presence: true

    belongs_to(
        :creator,
        class_name: "User",
        foreign_key: :creator_id,
        primary_key: :id
    )

end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
    before_action :require_current_user!
    before_action :set_goal, only: %i[show edit update destroy]
    before_action :require_goal_owner!, only: %i[edit update destroy]

    def new
        @goal = Goal.new
    end

    def create
        goal_params[:is_private] = (goal_params[:is_private] == "true") ? true : false
        goal_params[:is_complete] = (goal_params[:is_complete] == "true") ? true : false
        
        @goal = Goal.new(goal_params)

        if @goal.save
            redirect_to goal_url(@goal)
        else
            flash[:errors] = @goal.errors.full_messages
            render :new
        end
    end

    def show
        render :show
    end

    def edit
        render :edit
    end

    def update
        if @goal.update_attributes(goal_params)
            redirect_to goal_url(@goal)
        else
            flash[:errors] = @goal.errors.full_messages
            render :edit
        end
    end

    def destroy
        @user = @goal.creator
        @goal.destroy
        redirect_to user_url(@user)
    end


    private

    def set_goal
        @goal = Goal.find_by(id: params[:id])
    end

    def require_goal_owner!
        set_goal
        redirect_to new_session_url unless @goal.creator == current_user
    end

    def goal_params
        params.require(:goal).permit(:title, :description, :is_complete, :is_private, :creator_id)
    end
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/views/goals/_form.html.erb
<% action_url = (goal.persisted? ? goal_url(goal) : goals_url) %>
<% method = (goal.persisted? ? "patch" : "post") %>
<% submit_text = (goal.persisted? ? "Update Goal" : "Create Goal") %>


<form action="<%= action_url %>" method="post">
    <input type="hidden" name="_method" value="<%= method %>">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="hidden" name="goal[creator_id]" value="<%= current_user.id %>">

    <label for="goal_title">Title:</label>
    <input type="text" name="goal[title]" id="goal_title" value="<%= goal.title %>">
    <br>
    <br>

    <label>Mark as private?</label>
    
    <label for="goal_is_private">Yes</label>
    <input type="radio" name="goal[is_private]" id="goal_is_private" value="true" <%= "checked" if goal.is_private %>>

    <label for="goal_is_public">No</label>
    <input type="radio" name="goal[is_private]" id="goal_is_public" value="false" <%= "checked" unless goal.is_private %>>
    <br>
    <br>

    <label>Mark as complete?</label>
    
    <label for="goal_is_complete">Yes</label>
    <input type="radio" name="goal[is_complete]" id="goal_is_complete" value="true" <%= "checked" if goal.is_complete %>>

    <label for="goal_is_not_complete">No</label>
    <input type="radio" name="goal[is_complete]" id="goal_is_not_complete" value="false" <%= "checked" unless goal.is_complete %>>
    <br>
    <br>


    <label for="goal_description">Description(optional):</label>
    <br>
    <textarea name="goal[description]" id="goal_description" cols="30" rows="10"><%= goal.description %></textarea>
    <br>
    <br>

    <input type="submit" value="<%= submit_text %>">
</form>

app/views/goals/edit.html.erb
<h1>Update goal</h1>

<%= render 'form', goal: @goal %>

app/views/goals/new.html.erb
<h1>Create A New Goal</h1>

<%= render 'form', goal: @goal %>

app/views/goals/show.html.erb
<h1><%= @goal.title %></h1>

<p>Privacy Status: <%= @goal.is_private == true ? "Private" : "Public" %></p>
<p>Completion Status: <%= @goal.is_complete == true ? "Completed" : "In Progress" %></p>

<pre><%= @goal.description %></pre>

<a href="<%= edit_goal_url(@goal) %>">Update Goal</a>